### ISSUE TITLE
[1.14.4] Client Crash on load 

### ISSUE THREAD

**Issue by ProsperCraft** [Iunius118/ToLaserBlade#1]
Crash report -
https://gist.github.com/ProsperCraft/601934096a3d4221e9bcbae02247b770

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

It doesn't crash on the pc I made the pack with, but when installing it on another pc I had it, and a user had it.

**Comment by ProsperCraft** [comment]
FYI, running the pack a second and third time, I did not get this anymore on this other pc.

**Comment by Iunius118** [comment]
This has been fixed in version 1.14.4-2.0.3.2.

**Comment by ghost** [comment]
It returned in 2.0.4.1!

**Comment by Iunius118** [comment]
> It returned in 2.0.4.1!

I need your crash report to fix this.

**Comment by Iunius118** [comment]
This fixed in 2.0.4.2.
