### ISSUE TITLE
Support for Enchantment Descriptions

### ISSUE THREAD

**Issue by WenXin20** [Iunius118/ToLaserBlade#10]
- Support for this mod would only require `enchantment.tolaserblade.enchant_name.desc` to be added to the lang file.
- Mod link: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by Iunius118** [comment]
Now ToLaserBlade v1.16.5-4.3.1.0 supports Enchantment Descriptions.

**Comment by WenXin20** [comment]
Thanks!
