### ISSUE TITLE
Add a zh_cn lang file (Simplified Chinese)

### ISSUE THREAD

**Issue by tankyap** [Iunius118/ToLaserBlade#14]
so I make a zh_cn file for this mod.
You can add it if you wanted

{
  "enchantment.tolaserblade.light_element": "光元素",
  "enchantment.tolaserblade.light_element.desc": "在激光剑上稍微提升攻击伤害,并且对怪物和流浪者造成额外的伤害",
  "item.tolaserblade.laser_blade": "激光剑",
  "item.tolaserblade.laser_blade_fp": "激光剑",
  "itemGroup.tolaserblade.general": "ToLaserBlade",
  "upgrade.tolaserblade.fireproof": "燃烧抵抗力　8000"
}

**Comment by Iunius118** [comment]
Thanks for your translation!
I'll update the lang file in the next version.

**Comment by Iunius118** [comment]
I'm thinking of translating "upgrade.tolaserblade.fireproof" into "耐高温　8000". This is because the English translation "HEAT RESISTANT 8000" means that the laser blade can withstand a high temperature of 8000 K.
