### ISSUE TITLE
Laser blades have a chance to appear as a cat

### ISSUE THREAD

**Issue by crickita** [Iunius118/ToLaserBlade#17]
Occasionally, when starting up minecraft, all laser blade handles are cats, sometimes sitting and sometimes standing up.
The first time I saw it, I thought it was just a one-off thing. I have now seen it three times.
No other mods I have on should be causing it.
(could not add pictures due to it not showing up a fourth time)

- Minecraft version: 1.16.5
- Forge version: Forge 36.2.35
- ToLaserBlade version: 4.3.2.0

**Steps to Reproduce:**
 1. Download forge 36.2.35
 2. Then add ToLaserBlade
 3. There seems to be a percentage chance that it will be a cat

I am not fully sure if this is a feature or a bug. Please let me know.

**Comment by Iunius118** [comment]
This is a feature of this mod.

![FZucBv8aIAE3im5](https://user-images.githubusercontent.com/18502177/183896535-e65d97ea-f29a-4fdc-bf8b-9322ce1e23e5.jpg)

ToLaserBlade 1.16.5 has 20 secret laser blade shapes and I think what you saw is one of them. Its shape changes may occur depending on date.

**Comment by crickita** [comment]
Interesting. Is there any way (like with commands or something) to obtain certain laser blade variants? It's hilarious to hit mobs with a cat.
Edit: What are the other secret shapes? I have only seen cats.
Edit 2: I noticed that this only affects the basic model, not the others.

**Comment by Iunius118** [comment]
The most basic way is to obtain a new laser blade that day from a _Brand-new Laser Blade I_ or _II_. The newly obtained laser blade will store its date of acquisition as a model number, thereby retaining its shape. FYI, the model number can be found in the tooltip of the laser blade.
If your laser blade does not have a model number, you can save the date of the day as a model number by combining the laser blade with a crafting table on a smithing table.
These methods must be done on a specific day of the year.

**Comment by crickita** [comment]
Okay, thank you for the information.
