### ISSUE TITLE
Can't change blade color with stained glass.

### ISSUE THREAD

**Issue by ghost** [Iunius118/ToLaserBlade#18]
- Minecraft version: 
- Forge version: 
- ToLaserBlade version: 

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of bug:**

**Comment by Iunius118** [comment]
I need more information to support this issue. Please add information about the situation in which the issue occurred to the issue template.

**Comment by Iunius118** [comment]
Please tell me what Minecraft version and ToLaserBlade version you were using when the problem occurred. Also, if you have a screenshot of the problem occurred, please paste it.

**Comment by Iunius118** [comment]
When you are ready to give details of the issue, post the issue again.
