### ISSUE TITLE
Mod causing strange behavior with beds and doors

### ISSUE THREAD

**Issue by GrifVindh** [Iunius118/ToLaserBlade#2]
It took me a while to track this down to this mod because it was literally the last one I expected to be responsible for it, but I've tested a world with no mods, and the same world with only ToLaserBlade running, so it appears this is the culprit.

Essentially: when this mod is loaded, placing a bed down on the floor causes only the lower half of it to display. You can use the bed as normal, but in terms of minecraft physics it acts like only half a bed -- i.e., if you hit the block where the bed is visible, the bed reacts. If you hit the block where the second half should be (but isn't) the floor acts like it's getting hit.

The entire bed shows up if you leave and reload. Even with only half a bed you can still sleep in it.

The second issue has to do with doors. Basically, I can open a door and not be able to go through it. my character reacts as if I'm pushing against an invisible wall. If I open and close the door quickly a few times, I'll wind up in a situation where half the door is open, half the door is closed. A few more times and the door will open as normal and I'll be able to pass through.

I've attached screenshots of both issues.

I've only seen this in 1.14.4 - I also play 1.12.2 and it doesn't show up there.

![halfbed](https://user-images.githubusercontent.com/49014549/64036737-e3ef9780-cb21-11e9-88e2-d644ea7fe50b.png)
![halfdoor](https://user-images.githubusercontent.com/49014549/64036748-e94ce200-cb21-11e9-93e5-42181f5a99d6.png)

**Comment by Iunius118** [comment]
~~Could you tell me the forge and mod versions?~~
I confirmed this problem on Forge 28.0.75.
OK, I will fix it.

**Comment by Iunius118** [comment]
This was fixed in version 1.14.4-2.0.4.3.
Please try it.

**Comment by GrifVindh** [comment]
It appears to be fixed!
