### ISSUE TITLE
Client kicked from dedicated server when using 4.1.3.0

### ISSUE THREAD

**Issue by JoelZBub** [Iunius118/ToLaserBlade#9]
- Minecraft {version} : 1.16.5
- Forge {version} : 36.0.42
- ToLaserBlade {version} : 4 .1.3.0

Tested using only ToLaserBlade mod 

**Steps to Reproduce:**
 1. Install ToLaserBlade version 4.1.3.0 Beta on client and server
 2. Try to connect to server
 3. Get kicked

**Description of bug:**
Client can not connect to dedicated server when using version 4.1.3.0
Client Error message : `Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: com.github.iunius118.tolaserblade.item.crafting.ModelChangeRecipe cannot be cast to com.github.iunius118.tolaserblade.item.crafting.ColorRecipe`

 Server latest.log included 
https://gist.github.com/JoelZBub/7773a698d13d935f4bdd12800579390c

**Comment by JoelZBub** [comment]
Still present on 4.1.4.0

**Comment by Iunius118** [comment]
Thanks for your report.
That will be fixed in v1.16.4-4.1.4.1
